/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_interdisciplinar;

/**
 *
 * @author Vinícius
 */
public class CadastroPrato extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPrato
     */
    public CadastroPrato() {
        initComponents();
    }
    
    public Prato criarPrato(){
     Prato prato = new Prato();
     prato.setCod_prato(Integer.parseInt(txtCodigo.getText()));
     prato.setIngredientes(txtIngre.getText());
     prato.setNome_prato(txtNomePrato.getText());
     prato.setValor_prato(Double.parseDouble(txtPreco.getText()));
     
     return prato;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNomePrato = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        buttonCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIngre = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Pratos");
        getContentPane().setLayout(null);

        jLabel4.setText("Preço do Prato:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 250, 75, 14);
        getContentPane().add(txtPreco);
        txtPreco.setBounds(90, 240, 100, 30);

        jLabel3.setText("Ingredientes:");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 65, 14);
        getContentPane().add(msg);
        msg.setBounds(10, 370, 470, 83);

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 37, 14);
        getContentPane().add(txtNomePrato);
        txtNomePrato.setBounds(100, 70, 272, 30);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(70, 30, 75, 30);

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrar);
        buttonCadastrar.setBounds(1, 290, 100, 23);

        jLabel2.setText("Nome do Prato:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 75, 14);

        txtIngre.setColumns(20);
        txtIngre.setRows(5);
        jScrollPane1.setViewportView(txtIngre);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 330, 96);

        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(420, 290, 61, 23);

        jButton3.setText("Pesquiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 290, 110, 23);

        jButton5.setText("Alterar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(230, 290, 90, 23);

        jButton6.setText("Deletar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(330, 290, 80, 23);

        jLabel11.setText("*Para pesquisar, insira o código");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(150, 40, 300, 14);

        setBounds(0, 0, 511, 514);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // TODO add your handling code here:
        Prato prato = criarPrato();
        String resp = new PratoDAO().cadastrarPrato(prato);
        
        if(resp.equals("OK")){
            msg.setText("Prato Gravado com sucesso!");
        }else{
            msg.setText(resp);
        }
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Prato prato = new PratoDAO().consultarPrato(Integer.parseInt(txtCodigo.getText()));
        String valorPrato = Double.toString(prato.getValor_prato());
        String cod = Integer.toString(prato.getCod_prato());
        if(prato == null){
            msg.setText("Prato nao encontrado");
        }else{
            txtCodigo.setText(cod);
            txtIngre.setText(prato.getIngredientes());
            txtNomePrato.setText(prato.getNome_prato());
            txtPreco.setText(valorPrato);
            msg.setText("Prato encontrado");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Prato prato = criarPrato();
        String resp = new PratoDAO().alterarPrato(prato);

        if(resp.equals("OK")){
            msg.setText("Prato alterado com sucesso");
        }else{
            msg.setText((resp));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String resp = new PratoDAO().deletarPrato(Integer.parseInt(txtCodigo.getText()));

        if(resp.equals("OK")){
            msg.setText("Prato deletado com sucesso");
        }else{
            msg.setText(resp);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtIngre;
    private javax.swing.JTextField txtNomePrato;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
